# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30, verbose_name='Artist')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('notes', models.TextField(blank=True, verbose_name='Extra notes')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30, verbose_name='Song name')),
                ('song_lyrics', models.TextField(verbose_name='Lyrics')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs_artists.Band', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
