# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=256, verbose_name='Назва пісні')),
                ('song_lyrics', models.TextField(blank=True, verbose_name='Текст пісні')),
            ],
            options={
                'verbose_name': 'Пісенька',
                'verbose_name_plural': 'Пісеньки',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_name', models.CharField(max_length=256, verbose_name='Назва виконавця')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('song', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lyrics', serialize=False, to='songs_artists.Lyrics', verbose_name='Пісенька')),
            ],
            options={
                'verbose_name': 'Виконавець',
                'verbose_name_plural': 'Виконавці',
            },
        ),
        migrations.AddField(
            model_name='lyrics',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='songs_artists.Band', verbose_name='Виконавець'),
        ),
    ]
