# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=256, verbose_name='Назва виконавця')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Зображення')),
                ('notes', models.TextField(blank=True, verbose_name='Про виконавця')),
            ],
            options={
                'verbose_name': 'Виконавець',
                'verbose_name_plural': 'Виконавці',
            },
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=256, verbose_name='Назва пісні')),
                ('song_lyrics', models.TextField(blank=True, verbose_name='Текст пісні')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='songs_artists.Band', verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Пісенька',
                'verbose_name_plural': 'Пісеньки',
            },
        ),
        migrations.AddField(
            model_name='band',
            name='song',
            field=models.ManyToManyField(blank=True, to='songs_artists.Lyrics', verbose_name='Пісенька'),
        ),
    ]
